runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /pixi
  static_dir: pixi
- url: /resources
  static_dir: resources
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
